### ISSUE TITLE
Create Team Markdown

### ISSUE THREAD

**Issue by 5Dawe** [jakubsepiolo2001/COM619-AE1#10]
Need to make a markdown table in our shared git repository with our team members in it. then send Craig a link to this file.

**Comment by 5Dawe** [comment]
Created a markdown file with our team details in it.
Pushed it to the branch: 
https://github.com/jakubsepiolo2001/COM619-AE1/tree/documentation-files

**Comment by Tyler-Short1** [comment]
Reviewed by Tyler:
The markdown file looks to be correct and completed to the issues standard. Can be merged with main branch and moved to done.
